# # infra/k8s/payment-mongo-statefulset.yaml
# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: payment-mongo-statefulset # K8s will prefix pod names with this. Youâ€™ll get:
# spec:
#   serviceName: "payment-mongo"
#   replicas: 1  # set >1 for replica set
#   selector:
#     matchLabels:
#       app: payment-mongodb
#   template:
#     metadata:
#       labels:
#         app: payment-mongodb
#     spec:
#       containers:
#         - name: payment-mongo
#           image: mongo:latest

          
#           env:
          
#           - name: MONGO_INITDB_ROOT_USERNAME   #special environment variables that the official MongoDB Docker image recognizes.
#             valueFrom:
#               secretKeyRef:
#                 name: mongo-credentials
#                 key: username

#           - name: MONGO_INITDB_ROOT_PASSWORD  #special environment variables that the official MongoDB Docker image recognizes.
#             valueFrom:
#               secretKeyRef:
#                 name: mongo-credentials
#                 key: password

#           ports:
#             - containerPort: 27017
#               name: mongodb
#           volumeMounts:
#             - name: data
#               mountPath: /data/db
#   volumeClaimTemplates:
#     - metadata:
#         name: data
#       spec:
#         accessModes: ["ReadWriteOnce"]
#         resources:
#           requests:
#             storage: 5Gi

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: payment-mongo-service
# spec:
#   clusterIP: None
#   selector:
#     app: payment-mongodb
#   ports:
#     - port: 27017
#       name: mongodb
